In [1]:
# import libraries
import torch
from torch import nn
from torch.nn import functional as F
import torchvision
import torchvision.transforms as transforms
from torch.utils.data import DataLoader
from torch.autograd import Variable
from sklearn.model_selection import train_test_split,TimeSeriesSplit
from torchsummary import summary

In [2]:
import sys
sys.path.append("../")
sys.path.append("../../")

import os
import random
import numpy as np

import pandas as pd
import matplotlib.pyplot as plt
import datetime
from datetime import timedelta
from predict import predict
from open_data import open_data, create_global_batch,get_df_stats,apply_norm
from dataset import RadarDataset,RadarCollate
from simple_model import LSTM
from train import train

In [3]:
PATH_CSV="/Users/iris/Documents/radar_deep/Radar_Traffic_Counts.csv" #"/Users/clemencevast/Documents/Courses/MachineLearning/RadarTrafficData_files/Radar_Traffic_Counts.csv" #"/Users/iris/Documents/radar_deep/Radar_Traffic_Counts.csv"
radar_name=' CAPITAL OF TEXAS HWY / LAKEWOOD DR'

In [4]:
df1=open_data(PATH_CSV, direction="NB", radar=radar_name, year=2018)

In [5]:
batch_df=create_global_batch(df1, window_x_day=6, window_label_day=1, gap_acquisition=1, tot_len_day=365)

Building batch 0 
 x begin 2018-01-02 label begin 2018-01-08 end period 2018-12-23 
Building batch 1 
 x begin 2018-01-03 label begin 2018-01-09 end period 2018-12-23 
Building batch 2 
 x begin 2018-01-04 label begin 2018-01-10 end period 2018-12-23 
Building batch 3 
 x begin 2018-01-05 label begin 2018-01-11 end period 2018-12-23 
Building batch 4 
 x begin 2018-01-06 label begin 2018-01-12 end period 2018-12-23 
We do not have all the dates for the time period in label , 96 42
Building batch 4 
 x begin 2018-01-07 label begin 2018-01-13 end period 2018-12-23 
Building batch 4 
 x begin 2018-01-08 label begin 2018-01-14 end period 2018-12-23 
Building batch 4 
 x begin 2018-01-09 label begin 2018-01-15 end period 2018-12-23 
Building batch 4 
 x begin 2018-01-10 label begin 2018-01-16 end period 2018-12-23 
Building batch 4 
 x begin 2018-01-11 label begin 2018-01-17 end period 2018-12-23 
Building batch 4 
 x begin 2018-01-12 label begin 2018-01-18 end period 2018-12-23 
Building b

Building batch 63 
 x begin 2018-04-09 label begin 2018-04-15 end period 2018-12-23 
Building batch 64 
 x begin 2018-04-10 label begin 2018-04-16 end period 2018-12-23 
Building batch 65 
 x begin 2018-04-11 label begin 2018-04-17 end period 2018-12-23 
Building batch 66 
 x begin 2018-04-12 label begin 2018-04-18 end period 2018-12-23 
Building batch 67 
 x begin 2018-04-13 label begin 2018-04-19 end period 2018-12-23 
Building batch 68 
 x begin 2018-04-14 label begin 2018-04-20 end period 2018-12-23 
Building batch 69 
 x begin 2018-04-15 label begin 2018-04-21 end period 2018-12-23 
Building batch 70 
 x begin 2018-04-16 label begin 2018-04-22 end period 2018-12-23 
Building batch 71 
 x begin 2018-04-17 label begin 2018-04-23 end period 2018-12-23 
Building batch 72 
 x begin 2018-04-18 label begin 2018-04-24 end period 2018-12-23 
Building batch 73 
 x begin 2018-04-19 label begin 2018-04-25 end period 2018-12-23 
Building batch 74 
 x begin 2018-04-20 label begin 2018-04-26 end

Building batch 124 
 x begin 2018-07-12 label begin 2018-07-18 end period 2018-12-23 
Building batch 125 
 x begin 2018-07-13 label begin 2018-07-19 end period 2018-12-23 
Building batch 126 
 x begin 2018-07-14 label begin 2018-07-20 end period 2018-12-23 
Building batch 127 
 x begin 2018-07-15 label begin 2018-07-21 end period 2018-12-23 
Building batch 128 
 x begin 2018-07-16 label begin 2018-07-22 end period 2018-12-23 
Building batch 129 
 x begin 2018-07-17 label begin 2018-07-23 end period 2018-12-23 
Building batch 130 
 x begin 2018-07-18 label begin 2018-07-24 end period 2018-12-23 
Building batch 131 
 x begin 2018-07-19 label begin 2018-07-25 end period 2018-12-23 
We do not have all the dates for the time period in label , 96 71
Building batch 131 
 x begin 2018-07-20 label begin 2018-07-26 end period 2018-12-23 
We do not have all the dates for the time period in x , 576 551
Building batch 131 
 x begin 2018-07-21 label begin 2018-07-27 end period 2018-12-23 
We do not 

Building batch 175 
 x begin 2018-10-26 label begin 2018-11-01 end period 2018-12-23 
Building batch 176 
 x begin 2018-10-27 label begin 2018-11-02 end period 2018-12-23 
Building batch 177 
 x begin 2018-10-28 label begin 2018-11-03 end period 2018-12-23 
Building batch 178 
 x begin 2018-10-29 label begin 2018-11-04 end period 2018-12-23 
Building batch 179 
 x begin 2018-10-30 label begin 2018-11-05 end period 2018-12-23 
Building batch 180 
 x begin 2018-10-31 label begin 2018-11-06 end period 2018-12-23 
Building batch 181 
 x begin 2018-11-01 label begin 2018-11-07 end period 2018-12-23 
Building batch 182 
 x begin 2018-11-02 label begin 2018-11-08 end period 2018-12-23 
Building batch 183 
 x begin 2018-11-03 label begin 2018-11-09 end period 2018-12-23 
Building batch 184 
 x begin 2018-11-04 label begin 2018-11-10 end period 2018-12-23 
Building batch 185 
 x begin 2018-11-05 label begin 2018-11-11 end period 2018-12-23 
Building batch 186 
 x begin 2018-11-06 label begin 20

In [6]:
batch_df

vol_data_x  \
0    [22, 13, 21, 21, 15, 11, 19, 5, 14, 6, 5, 8, 4...   
1    [33.0, 31.0, 20.0, 22.0, 13.0, 13.0, 13.0, 9.0...   
2    [32.0, 31.0, 25.0, 29.0, 29.0, 10.0, 21.0, 17....   
3    [33.0, 37.0, 28.0, 19.0, 26.0, 16.0, 13.0, 14....   
4    [13.0, 5.0, 14.0, 15.0, 9.0, 4.0, 6.0, 1.0, 4....   
..                                                 ...   
202  [58, 28, 26, 33, 20, 23, 13, 15, 6, 7, 13, 5, ...   
203  [50, 40, 36, 22, 27, 22, 19, 27, 15, 12, 7, 9,...   
204  [70, 63, 57, 46, 38, 33, 25, 30, 24, 16, 10, 1...   
205  [87, 78, 75, 57, 45, 31, 35, 28, 26, 15, 10, 1...   
206  [80, 61, 67, 61, 31, 38, 24, 26, 31, 14, 20, 1...   

                                           vol_label_y  
0    [24.0, 21.0, 0.0, 0.0, 18.0, 10.0, 14.0, 10.0,...  
1    [66, 40, 40, 22, 28, 22, 13, 9, 10, 14, 17, 7,...  
2    [36, 32, 28, 26, 23, 20, 14, 21, 8, 9, 11, 9, ...  
3    [48, 32, 36, 28, 32, 23, 8, 22, 17, 7, 21, 15,...  
4    [33, 38, 45, 30, 25, 10, 13, 15, 4, 8, 4, 9, 1...  
..                                                 ...  
202  [38, 35, 29, 18, 11, 20, 11, 14, 9, 13, 6, 7, ...  
203  [41, 42, 32, 32, 20, 13, 22, 15, 10, 8, 5, 11,...  
204  [63, 52, 39, 29, 25, 17, 19, 18, 10, 8, 6, 9, ...  
205  [82, 87, 67, 69, 46, 32, 40, 27, 23, 19, 23, 1...  
206  [41, 43, 38, 35, 23, 25, 22, 23, 19, 16, 9, 12...  

[207 rows x 2 columns]

In [7]:
#batch_df["mean_x"]=batch_df["vol_data_x"].apply(lambda x : np.mean(x))
#batch_df["std_x"]=batch_df["vol_data_x"].apply(lambda x : np.std(x))
#batch_df["mean_y"]=batch_df["vol_label_y"].apply(lambda x : np.mean(x))
# batch_df

In [8]:
df_mean,df_std=get_df_stats(batch_df)
new_data=apply_norm(batch_df,df_mean,df_std)


In [9]:
get_df_stats(new_data,["vol_data_x_norm","vol_label_y_norm"])

(0.0, 1.0)

In [10]:
batch_df

vol_data_x  \
0    [22, 13, 21, 21, 15, 11, 19, 5, 14, 6, 5, 8, 4...   
1    [33.0, 31.0, 20.0, 22.0, 13.0, 13.0, 13.0, 9.0...   
2    [32.0, 31.0, 25.0, 29.0, 29.0, 10.0, 21.0, 17....   
3    [33.0, 37.0, 28.0, 19.0, 26.0, 16.0, 13.0, 14....   
4    [13.0, 5.0, 14.0, 15.0, 9.0, 4.0, 6.0, 1.0, 4....   
..                                                 ...   
202  [58, 28, 26, 33, 20, 23, 13, 15, 6, 7, 13, 5, ...   
203  [50, 40, 36, 22, 27, 22, 19, 27, 15, 12, 7, 9,...   
204  [70, 63, 57, 46, 38, 33, 25, 30, 24, 16, 10, 1...   
205  [87, 78, 75, 57, 45, 31, 35, 28, 26, 15, 10, 1...   
206  [80, 61, 67, 61, 31, 38, 24, 26, 31, 14, 20, 1...   

                                           vol_label_y  vol_data_x_min  \
0    [24.0, 21.0, 0.0, 0.0, 18.0, 10.0, 14.0, 10.0,...             3.0   
1    [66, 40, 40, 22, 28, 22, 13, 9, 10, 14, 17, 7,...             0.0   
2    [36, 32, 28, 26, 23, 20, 14, 21, 8, 9, 11, 9, ...             0.0   
3    [48, 32, 36, 28, 32, 23, 8, 22, 17, 7, 21, 15,...             0.0   
4    [33, 38, 45, 30, 25, 10, 13, 15, 4, 8, 4, 9, 1...             0.0   
..                                                 ...             ...   
202  [38, 35, 29, 18, 11, 20, 11, 14, 9, 13, 6, 7, ...             3.0   
203  [41, 42, 32, 32, 20, 13, 22, 15, 10, 8, 5, 11,...             3.0   
204  [63, 52, 39, 29, 25, 17, 19, 18, 10, 8, 6, 9, ...             3.0   
205  [82, 87, 67, 69, 46, 32, 40, 27, 23, 19, 23, 1...             3.0   
206  [41, 43, 38, 35, 23, 25, 22, 23, 19, 16, 9, 12...             2.0   

     vol_data_x_max  vol_label_y_min  vol_label_y_max  \
0             870.0              0.0            483.0   
1             870.0              4.0            474.0   
2             870.0              2.0            470.0   
3             483.0              5.0            477.0   
4             789.0              4.0            492.0   
..              ...              ...              ...   
202           488.0              4.0            484.0   
203           488.0              5.0            501.0   
204           501.0              6.0            480.0   
205           501.0              5.0            409.0   
206           461.0              6.0            437.0   

                                       vol_data_x_norm  \
0    [0.022610483042137718, 0.013360739979445015, 0...   
1    [0.03391572456320658, 0.03186022610483042, 0.0...   
2    [0.0328879753340185, 0.03186022610483042, 0.02...   
3    [0.03391572456320658, 0.03802672147995889, 0.0...   
4    [0.013360739979445015, 0.0051387461459403904, ...   
..                                                 ...   
202  [0.05960945529290853, 0.02877697841726619, 0.0...   
203  [0.051387461459403906, 0.041109969167523124, 0...   
204  [0.07194244604316546, 0.06474820143884892, 0.0...   
205  [0.08941418293936279, 0.08016443987667009, 0.0...   
206  [0.08221993833504625, 0.06269270298047276, 0.0...   

                                      vol_label_y_norm  vol_data_x_norm_min  \
0    [0.024665981500513873, 0.02158273381294964, 0....             0.003083   
1    [0.06783144912641316, 0.041109969167523124, 0....             0.000000   
2    [0.03699897225077081, 0.0328879753340185, 0.02...             0.000000   
3    [0.04933196300102775, 0.0328879753340185, 0.03...             0.000000   
4    [0.03391572456320658, 0.03905447070914697, 0.0...             0.000000   
..                                                 ...                  ...   
202  [0.03905447070914697, 0.03597122302158273, 0.0...             0.003083   
203  [0.0421377183967112, 0.04316546762589928, 0.03...             0.003083   
204  [0.06474820143884892, 0.05344295991778006, 0.0...             0.003083   
205  [0.0842754367934224, 0.08941418293936279, 0.06...             0.003083   
206  [0.0421377183967112, 0.044193216855087356, 0.0...             0.002055   

     vol_data_x_norm_max  vol_label_y_norm_min  vol_label_y_norm_max  
0               0.894142              0.000000          

In [11]:
new_data

vol_data_x  \
0    [22, 13, 21, 21, 15, 11, 19, 5, 14, 6, 5, 8, 4...   
1    [33.0, 31.0, 20.0, 22.0, 13.0, 13.0, 13.0, 9.0...   
2    [32.0, 31.0, 25.0, 29.0, 29.0, 10.0, 21.0, 17....   
3    [33.0, 37.0, 28.0, 19.0, 26.0, 16.0, 13.0, 14....   
4    [13.0, 5.0, 14.0, 15.0, 9.0, 4.0, 6.0, 1.0, 4....   
..                                                 ...   
202  [58, 28, 26, 33, 20, 23, 13, 15, 6, 7, 13, 5, ...   
203  [50, 40, 36, 22, 27, 22, 19, 27, 15, 12, 7, 9,...   
204  [70, 63, 57, 46, 38, 33, 25, 30, 24, 16, 10, 1...   
205  [87, 78, 75, 57, 45, 31, 35, 28, 26, 15, 10, 1...   
206  [80, 61, 67, 61, 31, 38, 24, 26, 31, 14, 20, 1...   

                                           vol_label_y  vol_data_x_min  \
0    [24.0, 21.0, 0.0, 0.0, 18.0, 10.0, 14.0, 10.0,...             3.0   
1    [66, 40, 40, 22, 28, 22, 13, 9, 10, 14, 17, 7,...             0.0   
2    [36, 32, 28, 26, 23, 20, 14, 21, 8, 9, 11, 9, ...             0.0   
3    [48, 32, 36, 28, 32, 23, 8, 22, 17, 7, 21, 15,...             0.0   
4    [33, 38, 45, 30, 25, 10, 13, 15, 4, 8, 4, 9, 1...             0.0   
..                                                 ...             ...   
202  [38, 35, 29, 18, 11, 20, 11, 14, 9, 13, 6, 7, ...             3.0   
203  [41, 42, 32, 32, 20, 13, 22, 15, 10, 8, 5, 11,...             3.0   
204  [63, 52, 39, 29, 25, 17, 19, 18, 10, 8, 6, 9, ...             3.0   
205  [82, 87, 67, 69, 46, 32, 40, 27, 23, 19, 23, 1...             3.0   
206  [41, 43, 38, 35, 23, 25, 22, 23, 19, 16, 9, 12...             2.0   

     vol_data_x_max  vol_label_y_min  vol_label_y_max  \
0             870.0              0.0            483.0   
1             870.0              4.0            474.0   
2             870.0              2.0            470.0   
3             483.0              5.0            477.0   
4             789.0              4.0            492.0   
..              ...              ...              ...   
202           488.0              4.0            484.0   
203           488.0              5.0            501.0   
204           501.0              6.0            480.0   
205           501.0              5.0            409.0   
206           461.0              6.0            437.0   

                                       vol_data_x_norm  \
0    [0.022610483042137718, 0.013360739979445015, 0...   
1    [0.03391572456320658, 0.03186022610483042, 0.0...   
2    [0.0328879753340185, 0.03186022610483042, 0.02...   
3    [0.03391572456320658, 0.03802672147995889, 0.0...   
4    [0.013360739979445015, 0.0051387461459403904, ...   
..                                                 ...   
202  [0.05960945529290853, 0.02877697841726619, 0.0...   
203  [0.051387461459403906, 0.041109969167523124, 0...   
204  [0.07194244604316546, 0.06474820143884892, 0.0...   
205  [0.08941418293936279, 0.08016443987667009, 0.0...   
206  [0.08221993833504625, 0.06269270298047276, 0.0...   

                                      vol_label_y_norm  vol_data_x_norm_min  \
0    [0.024665981500513873, 0.02158273381294964, 0....             0.003083   
1    [0.06783144912641316, 0.041109969167523124, 0....             0.000000   
2    [0.03699897225077081, 0.0328879753340185, 0.02...             0.000000   
3    [0.04933196300102775, 0.0328879753340185, 0.03...             0.000000   
4    [0.03391572456320658, 0.03905447070914697, 0.0...             0.000000   
..                                                 ...                  ...   
202  [0.03905447070914697, 0.03597122302158273, 0.0...             0.003083   
203  [0.0421377183967112, 0.04316546762589928, 0.03...             0.003083   
204  [0.06474820143884892, 0.05344295991778006, 0.0...             0.003083   
205  [0.0842754367934224, 0.08941418293936279, 0.06...             0.003083   
206  [0.0421377183967112, 0.044193216855087356, 0.0...             0.002055   

     vol_data_x_norm_max  vol_label_y_norm_min  vol_label_y_norm_max  
0               0.894142              0.000000          

In [12]:
#get_df_stats(new_data,columns=["vol_data_x_norm","vol_label_y_norm"])

In [13]:
# sample_rate = 16000
batch_size = 1

In [14]:
#normalize=transforms.Compose([
#    transforms.ToTensor(),
  #  transforms.Normalize(mean=[df_mean],
                       #  std=[df_std])
#])
fullset = RadarDataset(dataframe=batch_df,transform=None)
ptrain,pval,ptest=0.8,0.05,0.15
trainglobdataset, testdataset = train_test_split(fullset, test_size=ptest,shuffle=False)
traindataset, valdataset = train_test_split(trainglobdataset, test_size=pval/(1-ptest),shuffle=False)

(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,)
(96,

In [15]:
collate_fn = RadarCollate()
trainloader = DataLoader(traindataset, batch_size=batch_size, collate_fn=collate_fn, shuffle=True)
valloader = DataLoader(valdataset, batch_size=batch_size, collate_fn=collate_fn, shuffle=True)
testloader = DataLoader(testdataset, batch_size=batch_size, collate_fn=collate_fn, shuffle=True)

In [16]:
print(traindataset)

[(array([0.02261048, 0.01336074, 0.02158273, 0.02158273, 0.01541624,
       0.01130524, 0.01952724, 0.00513875, 0.01438849, 0.0061665 ,
       0.00513875, 0.00822199, 0.004111  , 0.00719424, 0.01130524,
       0.00924974, 0.00822199, 0.00822199, 0.01336074, 0.02261048,
       0.02980473, 0.03494347, 0.03905447, 0.05755396, 0.08119219,
       0.10174717, 0.12846865, 0.22610483, 0.21891059, 0.2672148 ,
       0.32271326, 0.40390545, 0.41315519, 0.35149024, 0.44604317,
       0.36176773, 0.45940391, 0.35662898, 0.34121274, 0.36690647,
       0.37410072, 0.35457348, 0.30832477, 0.327852  , 0.28365879,
       0.32887975, 0.38437821, 0.34635149, 0.41007194, 0.41315519,
       0.4049332 , 0.41932169, 0.39362795, 0.37204522, 0.37512847,
       0.40390545, 0.34737924, 0.37512847, 0.34532374, 0.44707091,
       0.336074  , 0.38540596, 0.44193217, 0.42651593, 0.43576567,
       0.23021583, 0.26618705, 0.48612539, 0.22096608, 0.46659815,
       0.46248715, 0.46248715, 0.45632066, 0.49023638, 0.353

In [17]:
c= 0
for x in trainloader:
    print("batch number {}".format(c))
    print(x[0].shape, x[1].shape, "\n")
    print(x)
    c+=1

batch number 0
torch.Size([1, 576]) torch.Size([1, 96]) 

(tensor([[0.0504, 0.0514, 0.0586, 0.0462, 0.0267, 0.0226, 0.0226, 0.0154, 0.0175,
         0.0175, 0.0154, 0.0113, 0.0123, 0.0092, 0.0164, 0.0082, 0.0185, 0.0154,
         0.0113, 0.0092, 0.0216, 0.0216, 0.0452, 0.0442, 0.0493, 0.0761, 0.1007,
         0.1501, 0.1757, 0.2549, 0.3032, 0.3762, 0.8284, 0.3474, 0.3494, 0.4409,
         0.3967, 0.3546, 0.3792, 0.3350, 0.3741, 0.3371, 0.3782, 0.3484, 0.3649,
         0.3649, 0.4368, 0.3875, 0.4296, 0.4080, 0.4234, 0.4101, 0.3854, 0.3967,
         0.4049, 0.4080, 0.6043, 0.4203, 0.3885, 0.4234, 0.4224, 0.3628, 0.4419,
         0.4286, 0.2097, 0.4512, 0.4779, 0.2271, 0.4769, 0.2580, 0.2364, 0.5067,
         0.4347, 0.3638, 0.4018, 0.4132, 0.4306, 0.3515, 0.3607, 0.2734, 0.2631,
         0.2312, 0.2302, 0.2456, 0.2467, 0.2117, 0.1583, 0.1357, 0.2086, 0.1778,
         0.1480, 0.1542, 0.1120, 0.1059, 0.1007, 0.0894, 0.0832, 0.0678, 0.0606,
         0.0452, 0.0493, 0.0339, 0.0319, 0.0329, 0

(tensor([[0.0586, 0.0401, 0.0370, 0.0349, 0.0319, 0.0164, 0.0247, 0.0144, 0.0185,
         0.0123, 0.0113, 0.0113, 0.0082, 0.0134, 0.0113, 0.0113, 0.0082, 0.0164,
         0.0113, 0.0134, 0.0144, 0.0257, 0.0432, 0.0391, 0.0678, 0.0946, 0.1028,
         0.1572, 0.2035, 0.2508, 0.3042, 0.3556, 0.4029, 0.3977, 0.7831, 0.4080,
         0.4830, 0.3977, 0.3268, 0.3207, 0.3515, 0.3525, 0.3700, 0.3597, 0.3905,
         0.4173, 0.4224, 0.4296, 0.4101, 0.3546, 0.3803, 0.3720, 0.3885, 0.3916,
         0.4224, 0.3772, 0.4018, 0.3957, 0.3864, 0.3905, 0.3905, 0.3926, 0.4306,
         0.9024, 0.2415, 0.4152, 0.4851, 0.4717, 0.4841, 0.4902, 0.2549, 0.2343,
         0.4532, 0.4758, 0.4173, 0.3392, 0.4306, 0.3371, 0.3844, 0.3268, 0.2744,
         0.2600, 0.2405, 0.2055, 0.1922, 0.1942, 0.1593, 0.2097, 0.1973, 0.1686,
         0.1778, 0.1531, 0.1429, 0.1295, 0.1089, 0.1069, 0.1007, 0.0791, 0.0534,
         0.0617, 0.0360, 0.0380, 0.0298, 0.0288, 0.0175, 0.0134, 0.0113, 0.0175,
         0.0216, 0.0144, 0.

(tensor([[0.0956, 0.0884, 0.0555, 0.0452, 0.0329, 0.0370, 0.0288, 0.0308, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0206, 0.0216, 0.0247, 0.0164, 0.0226, 0.0195,
         0.0206, 0.0123, 0.0185, 0.0154, 0.0175, 0.0195, 0.0247, 0.0185, 0.0247,
         0.0442, 0.0391, 0.0442, 0.0360, 0.0452, 0.0689, 0.0493, 0.0894, 0.0966,
         0.1305, 0.1254, 0.1377, 0.1706, 0.1912, 0.1644, 0.2302, 0.2189, 0.3268,
         0.3032, 0.2919, 0.2816, 0.3350, 0.2857, 0.3443, 0.4265, 0.3834, 0.3114,
         0.3104, 0.3032, 0.2816, 0.2878, 0.2795, 0.2991, 0.2878, 0.2744, 0.2775,
         0.2816, 0.2621, 0.2610, 0.2652, 0.2539, 0.2734, 0.2210, 0.2374, 0.2097,
         0.2405, 0.2055, 0.2189, 0.2148, 0.2004, 0.2004, 0.2261, 0.1860, 0.1819,
         0.1603, 0.1757, 0.1367, 0.1316, 0.1295, 0.1367, 0.1038, 0.1038, 0.1038,
         0.1223, 0.0904, 0.0699, 0.0771, 0.0555, 0.0524, 0.0534, 0.0329, 0.0298,
         0.0226, 0.0175, 0.0123, 0.0175, 0.0144, 0.0072, 0.1901, 0.0103, 0.0134,
         0.0134, 0.0103, 0.

(tensor([[0.0380, 0.0349, 0.0298, 0.0298, 0.0206, 0.0154, 0.0134, 0.0082, 0.0092,
         0.0144, 0.0092, 0.0123, 0.0082, 0.0041, 0.0062, 0.0072, 0.0154, 0.0154,
         0.0175, 0.0206, 0.0195, 0.0565, 0.0391, 0.0545, 0.0997, 0.1254, 0.1634,
         0.2055, 0.2569, 0.3330, 0.4090, 0.4594, 0.4121, 0.3720, 0.4347, 0.3772,
         0.4358, 0.3587, 0.4008, 0.4173, 0.3679, 0.3659, 0.3433, 0.3361, 0.3731,
         0.3998, 0.3577, 0.4481, 0.3546, 0.3916, 0.3844, 0.4368, 0.3690, 0.3720,
         0.3649, 0.3998, 0.4039, 0.3649, 0.3679, 0.4224, 0.4029, 0.4214, 0.4214,
         0.4286, 0.1891, 0.2199, 0.4738, 0.2816, 0.2282, 0.4430, 0.2384, 0.2446,
         0.4954, 0.2374, 0.4769, 0.4532, 0.4234, 0.3525, 0.3279, 0.2631, 0.2261,
         0.2251, 0.1665, 0.1850, 0.1634, 0.1727, 0.1655, 0.1552, 0.1655, 0.1161,
         0.1470, 0.1100, 0.0832, 0.0822, 0.0565, 0.0576, 0.0504, 0.0339, 0.0329,
         0.0319, 0.0247, 0.0206, 0.0134, 0.0113, 0.0175, 0.0082, 0.0113, 0.0103,
         0.0123, 0.0144, 0.

(tensor([[0.0452, 0.0504, 0.0380, 0.0360, 0.0236, 0.0175, 0.0195, 0.0134, 0.0216,
         0.0154, 0.0092, 0.0175, 0.0144, 0.0154, 0.0092, 0.0082, 0.0113, 0.0051,
         0.0092, 0.0195, 0.0236, 0.0524, 0.0370, 0.0586, 0.0997, 0.1110, 0.1470,
         0.1819, 0.2600, 0.2878, 0.3957, 0.4008, 0.3977, 0.3638, 0.3577, 0.4193,
         0.4039, 0.4039, 0.3803, 0.3947, 0.3525, 0.3186, 0.3628, 0.3587, 0.3381,
         0.4121, 0.4039, 0.3947, 0.4101, 0.3885, 0.4245, 0.4049, 0.3957, 0.7677,
         0.3679, 0.3803, 0.3895, 0.4142, 0.3700, 0.4029, 0.3854, 0.4317, 0.4090,
         0.4378, 0.2117, 0.2025, 0.4933, 0.4913, 0.4800, 0.4584, 0.2354, 0.4584,
         0.4717, 0.4224, 0.4358, 0.3998, 0.3309, 0.3453, 0.3535, 0.3094, 0.2652,
         0.2343, 0.2251, 0.2086, 0.1757, 0.1614, 0.1819, 0.1757, 0.1377, 0.1326,
         0.1809, 0.1531, 0.1172, 0.1213, 0.0874, 0.0812, 0.0699, 0.0791, 0.0658,
         0.0401, 0.0493, 0.0360, 0.0247, 0.0216, 0.0206, 0.0175, 0.0082, 0.0144,
         0.0236, 0.0134, 0.

(tensor([[0.0288, 0.0339, 0.0329, 0.0216, 0.0134, 0.0113, 0.0154, 0.0164, 0.0123,
         0.0134, 0.0103, 0.0051, 0.0072, 0.0062, 0.0092, 0.0082, 0.0103, 0.0092,
         0.0134, 0.0206, 0.0277, 0.0432, 0.0432, 0.0545, 0.0956, 0.1079, 0.1367,
         0.2045, 0.2621, 0.3176, 0.3762, 0.4419, 0.4152, 0.4347, 0.4049, 0.4553,
         0.4018, 0.3792, 0.3700, 0.3977, 0.3299, 0.3443, 0.3659, 0.3597, 0.3402,
         0.3464, 0.3361, 0.4173, 0.3885, 0.3834, 0.3916, 0.3823, 0.3916, 0.4049,
         0.4142, 0.3484, 0.3607, 0.3535, 0.4306, 0.3505, 0.3905, 0.3741, 0.4193,
         0.3618, 0.4656, 0.2076, 0.2302, 0.4789, 0.4717, 0.2497, 0.4666, 0.0288,
         0.4728, 0.2405, 0.2230, 0.3988, 0.3659, 0.3669, 0.3649, 0.3022, 0.2343,
         0.2528, 0.1932, 0.2035, 0.1963, 0.1778, 0.1583, 0.1501, 0.1459, 0.1387,
         0.1100, 0.0802, 0.0689, 0.0668, 0.0647, 0.0627, 0.0504, 0.0401, 0.0339,
         0.0216, 0.0185, 0.0175, 0.0195, 0.0175, 0.0062, 0.0123, 0.0144, 0.0113,
         0.0123, 0.0051, 0.

(tensor([[0.0298, 0.0277, 0.0216, 0.0277, 0.0195, 0.0195, 0.0185, 0.0144, 0.0062,
         0.0072, 0.0082, 0.0082, 0.0103, 0.0072, 0.0072, 0.0092, 0.0113, 0.0103,
         0.0103, 0.0175, 0.0319, 0.0349, 0.0483, 0.0771, 0.1048, 0.1007, 0.1254,
         0.2097, 0.2662, 0.2631, 0.3535, 0.3433, 0.3145, 0.3494, 0.4553, 0.3967,
         0.4039, 0.4049, 0.3803, 0.4203, 0.3864, 0.4409, 0.3659, 0.3638, 0.3453,
         0.3104, 0.3443, 0.3638, 0.3792, 0.3762, 0.3947, 0.3751, 0.3217, 0.3176,
         0.3268, 0.3813, 0.3011, 0.3083, 0.3535, 0.3772, 0.3186, 0.3977, 0.3967,
         0.3700, 0.2076, 0.4491, 0.2076, 0.4625, 0.2169, 0.2508, 0.4615, 0.4810,
         0.4306, 0.3957, 0.3628, 0.2888, 0.3186, 0.2816, 0.2806, 0.2323, 0.2497,
         0.1881, 0.1953, 0.1408, 0.1213, 0.1151, 0.1336, 0.1398, 0.1192, 0.0935,
         0.1120, 0.0915, 0.0627, 0.0617, 0.0462, 0.0360, 0.0462, 0.0267, 0.0319,
         0.0216, 0.0164, 0.0175, 0.0154, 0.0103, 0.0144, 0.0062, 0.0051, 0.0062,
         0.0113, 0.0041, 0.

(tensor([[0.0391, 0.0185, 0.0319, 0.0226, 0.0175, 0.0185, 0.0103, 0.0103, 0.0123,
         0.0072, 0.0051, 0.0103, 0.0103, 0.0041, 0.0092, 0.0113, 0.0092, 0.0103,
         0.0103, 0.0216, 0.0216, 0.0401, 0.0504, 0.0647, 0.1151, 0.1100, 0.1408,
         0.2086, 0.2590, 0.3207, 0.3936, 0.4327, 0.4111, 0.3895, 0.4327, 0.4173,
         0.4707, 0.3813, 0.3268, 0.3813, 0.3597, 0.3474, 0.3381, 0.3402, 0.3587,
         0.3464, 0.3607, 0.3998, 0.3659, 0.3741, 0.3741, 0.3248, 0.3792, 0.3762,
         0.4080, 0.3361, 0.3227, 0.3628, 0.3248, 0.4193, 0.3895, 0.4080, 0.3926,
         0.4018, 0.4676, 0.2127, 0.2179, 0.2395, 0.2456, 0.4933, 0.4995, 0.4913,
         0.2569, 0.2477, 0.1932, 0.3988, 0.4347, 0.4039, 0.3443, 0.2600, 0.2302,
         0.2631, 0.2251, 0.1562, 0.1531, 0.1511, 0.1449, 0.1285, 0.1223, 0.1089,
         0.1244, 0.0791, 0.0761, 0.0617, 0.0545, 0.0421, 0.0432, 0.0267, 0.0308,
         0.0164, 0.0226, 0.0113, 0.0134, 0.0113, 0.0134, 0.0103, 0.0092, 0.0103,
         0.0103, 0.0134, 0.

(tensor([[0.0483, 0.0267, 0.0370, 0.0144, 0.0195, 0.0144, 0.0164, 0.0123, 0.0134,
         0.0082, 0.0072, 0.0123, 0.0103, 0.0072, 0.0092, 0.0103, 0.0092, 0.0134,
         0.0298, 0.0144, 0.0236, 0.0504, 0.0534, 0.0678, 0.0987, 0.1316, 0.1583,
         0.2127, 0.3268, 0.4132, 0.4707, 0.0421, 0.2693, 0.2374, 0.2549, 0.2395,
         0.0206, 0.2271, 0.4615, 0.4193, 0.4707, 0.3875, 0.3628, 0.3813, 0.3977,
         0.4203, 0.4214, 0.4676, 0.4440, 0.3864, 0.4491, 0.4460, 0.4717, 0.4132,
         0.4060, 0.4142, 0.4306, 0.4029, 0.4111, 0.4882, 0.4255, 0.4656, 0.4769,
         0.2405, 0.2754, 0.3104, 0.1285, 0.3279, 0.2970, 0.0606, 0.0442, 0.0411,
         0.0504, 0.2662, 0.2724, 0.2795, 0.4758, 0.3936, 0.3042, 0.2518, 0.2549,
         0.2127, 0.1922, 0.1459, 0.1665, 0.1634, 0.1305, 0.1490, 0.1634, 0.1336,
         0.0976, 0.0956, 0.0709, 0.0576, 0.0349, 0.0534, 0.0329, 0.0370, 0.0216,
         0.0339, 0.0236, 0.0154, 0.0082, 0.0103, 0.0072, 0.0123, 0.0123, 0.0051,
         0.0072, 0.0123, 0.

(tensor([[0.0380, 0.0349, 0.0257, 0.0144, 0.0195, 0.0144, 0.0072, 0.0072, 0.0103,
         0.0175, 0.0103, 0.0195, 0.0062, 0.0051, 0.0082, 0.0319, 0.0082, 0.0082,
         0.0144, 0.0236, 0.0370, 0.0442, 0.0391, 0.0689, 0.0915, 0.1202, 0.1675,
         0.2518, 0.3237, 0.4090, 0.4810, 0.5077, 0.0401, 0.4419, 0.2672, 0.4738,
         0.2693, 0.2456, 0.2343, 0.2703, 0.4584, 0.4502, 0.3731, 0.4234, 0.3885,
         0.4049, 0.4203, 0.4388, 0.3803, 0.3864, 0.3926, 0.4234, 0.2210, 0.3895,
         0.4306, 0.4080, 0.3618, 0.3936, 0.4018, 0.4060, 0.4070, 0.4265, 0.4265,
         0.4779, 0.2549, 0.0637, 0.0514, 0.2302, 0.2662, 0.2395, 0.0473, 0.0401,
         0.2734, 0.0144, 0.2395, 0.2312, 0.3905, 0.3330, 0.3135, 0.2775, 0.2271,
         0.1891, 0.1696, 0.1336, 0.1408, 0.1295, 0.1593, 0.1244, 0.1089, 0.1089,
         0.1151, 0.0832, 0.0606, 0.0504, 0.0308, 0.0349, 0.0329, 0.0360, 0.0236,
         0.0226, 0.0103, 0.0113, 0.0144, 0.0103, 0.0082, 0.0092, 0.0051, 0.0092,
         0.0092, 0.0092, 0.

(tensor([[0.0442, 0.0277, 0.0277, 0.0113, 0.0154, 0.0144, 0.0072, 0.0154, 0.0144,
         0.0082, 0.0144, 0.0082, 0.0072, 0.0082, 0.0123, 0.0154, 0.0123, 0.0144,
         0.0226, 0.0308, 0.0288, 0.0349, 0.0462, 0.0647, 0.1069, 0.1182, 0.1716,
         0.2508, 0.2693, 0.3525, 0.4317, 0.4378, 0.4378, 0.4409, 0.4481, 0.4111,
         0.4234, 0.3782, 0.4245, 0.4049, 0.3464, 0.3217, 0.3433, 0.3422, 0.3895,
         0.3402, 0.3875, 0.4162, 0.4440, 0.3720, 0.4502, 0.3628, 0.3731, 0.3731,
         0.3823, 0.3453, 0.3638, 0.3402, 0.3864, 0.4183, 0.4440, 0.3905, 0.4337,
         0.3649, 0.2446, 0.2251, 0.4738, 0.2549, 0.4902, 0.4820, 0.2580, 0.4851,
         0.4553, 0.5170, 0.2600, 0.2425, 0.4512, 0.3607, 0.3577, 0.3217, 0.2425,
         0.2230, 0.2158, 0.1768, 0.1531, 0.1418, 0.1387, 0.1614, 0.1172, 0.1151,
         0.1100, 0.0976, 0.0514, 0.0689, 0.0617, 0.0493, 0.0370, 0.0206, 0.0277,
         0.0195, 0.0134, 0.0092, 0.0154, 0.0072, 0.0123, 0.0072, 0.0185, 0.0103,
         0.0072, 0.0031, 0.

## Modèle 1 

In [18]:
input_dim = 576    
hidden_dim = 256
layer_dim = 2
output_dim = 96
seq_dim = 1

lr = 0.05
n_epochs = 300
iterations_per_epoch = len(trainloader)
name_model = "simple_model_smalldataset_lr5e-2"

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device
model=LSTM()


In [19]:
print(model)

LSTM(
  (lstm): LSTM(576, 100)
  (linear): Linear(in_features=100, out_features=96, bias=True)
)


In [ ]:
iteration,loss_train_list,loss_val_list=train(model, trainloader, valloader, lr=lr, n_epochs=n_epochs, name_model=name_model, device=device, ite_print=5,save=True)

/Users/iris/opt/anaconda3/envs/dl_env/lib/python3.7/site-packages/torch/nn/modules/loss.py:431: UserWarning: Using a target size (torch.Size([1, 96])) that is different to the input size (torch.Size([96])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


epoch 1 loss train 0.01346095185726881 loss val 0.00864491518586874


/Users/iris/opt/anaconda3/envs/dl_env/lib/python3.7/site-packages/torch/serialization.py:292: UserWarning: Couldn't retrieve source code for container of type LSTM. It won't be checked for correctness upon loading.
  "type " + obj.__name__ + ". It won't be checked "
/Users/iris/opt/anaconda3/envs/dl_env/lib/python3.7/site-packages/torch/serialization.py:292: UserWarning: Couldn't retrieve source code for container of type Linear. It won't be checked for correctness upon loading.
  "type " + obj.__name__ + ". It won't be checked "


epoch 6 loss train 0.012464423663914204 loss val 0.009426052682101727
epoch 11 loss train 0.005737310275435448 loss val 0.00897990632802248
epoch 16 loss train 0.01695643924176693 loss val 0.010229705832898617
epoch 21 loss train 0.0049799345433712006 loss val 0.0076873269863426685
epoch 26 loss train 0.003718818072229624 loss val 0.010999433696269989
epoch 31 loss train 0.005951269064098597 loss val 0.011421123519539833
epoch 36 loss train 0.004800610709935427 loss val 0.010523149743676186
epoch 41 loss train 0.0030196530278772116 loss val 0.008541878312826157
epoch 46 loss train 0.0049306657165288925 loss val 0.011127964593470097
epoch 51 loss train 0.006515130400657654 loss val 0.008271360769867897
epoch 56 loss train 0.010532153770327568 loss val 0.007217415142804384
epoch 61 loss train 0.011167791672050953 loss val 0.007032082881778479
epoch 66 loss train 0.010530880652368069 loss val 0.008748232387006283
epoch 71 loss train 0.0057089370675385 loss val 0.008053204976022243
epoch 7

In [ ]:
fig,ax=plt.subplots()
ax.plot(iteration,loss_train_list,"b",label="loss train")
ax.plot(iteration,loss_val_list,"r",label="loss validation")
ax.legend()

## Modèle 2 

In [ ]:
input_dim = 576    
hidden_dim = 256
layer_dim = 2
output_dim = 96
seq_dim = 1

lr2 = 0.001
n_epochs = 500
iterations_per_epoch = len(trainloader)
#name_model = "model2"


device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

model=LSTM()
name_model="simple_model_smalldataset_lre-3"


In [ ]:
iteration2,loss_train_list2,loss_val_list2=train(model, trainloader, valloader, lr=lr2, n_epochs=n_epochs, name_model=name_model, device=device,ite_print=2,save=False)

In [ ]:
fig,ax=plt.subplots()
ax.plot(iteration2,loss_train_list2,"b",label="loss train")
ax.plot(iteration2,loss_val_list2,"r",label="loss validation")
ax.legend()

In [ ]:
fig,ax=plt.subplots()
ax.set_title("Ssimple model")
ax.plot(iteration,loss_val_list,"green",label="loss validation lr 5e-2")
ax.plot(iteration2,loss_val_list2,"r",label="loss validation lr 1e-3")
ax.legend()

In [ ]:
PATH_MODEL="/Users/iris/Code/RadarTrafficData/models/simple_model_smalldataset_lr5e-2.pt"
prediction, gt, mse_list=predict(PATH_MODEL,testloader)

In [ ]:
for i,b in testloader:
    print(i)

In [ ]:
#print(prediction)
print(gt)

In [ ]:
fig,ax=plt.subplots(2,1)
arr_pred=prediction[0].detach().numpy()
ax[0].plot([i for i in range(len(arr_pred))],arr_pred)
arr_gt=gt[0].detach().numpy()
ax[0].plot([i for i in range(len(arr_pred))],arr_gt.ravel(),"r")